version: 2.1

jobs:
    create-infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                  name: Create Cloudformation Stack
                  command: |
                      aws cloudformation deploy \
                      --template-file template.yml \
                      --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                      --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
                      --region us-east-1

    configure_infrastructure:
        docker:
            - image: python:3.7-alpine3.11
        steps:
            - checkout
            - add_ssh_keys:
                  fingerprints:
                      ["80:23:b1:d4:f6:2b:23:68:4a:4c:c6:81:d3:94:4b:9c"]
            - run:
                  name: Install Ansible
                  command: |
                      apk add --update ansible
            - run:
                  name: Run Playbook and Configure server
                  command: |
                      ansible-playbook -i host playbook.yml
workflows:
    my-workflow:
        jobs:
            # - create-infrastructure
            - configure_infrastructure
