version: 2.1

jobs:
    create-infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                  name: Create Cloudformation Stack
                  command: |
                      aws cloudformation deploy \
                        --template-file template.yaml \
                        --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                        --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
                        --region us-east-2
            - run: aws cloudformation describe-stack-events --stack-name myStack-fa8da

workflows:
    my-workflow:
        jobs:
            - create-infrastructure
